// Contratos tipados compartidos entre mobile y web.

export type { RolUsuario, EstadoTicket, PrioridadTicket } from './types.js';
export type { Ticket as TicketBase } from './types.js';
export * from './roles.js';
export * from './permissions.js';
export * from './supabase.js';
export * from './auth.js';
export * from './password.js';
export type { TicketCategoria, Mesa, Ticket, TicketEstado, TicketComentario, TicketAdjunto, TicketDetail, CreateTicketInput, CreateTicketErrors, ListMyTicketsParams, ListMyTicketsResult, UpdateTicketInput, ListAssignedParams } from './tickets.js';
export { PRIORIDADES, ESTADOS, isPrioridadTicket, isEstadoTicket, validateCreateTicket, isCreateTicketValid, validateComentario, validateAdjunto, validateAdjuntos, ADJUNTO_MAX_BYTES, ADJUNTO_MAX_COUNT, ADJUNTO_ALLOWED_MIMES, fetchCategorias, fetchMesas, createTicket, listMyTickets, getTicketDetail, fetchAdjuntos, addComentario, updateTicket, cancelTicket, transitionTicket, canTransition, reassignTicket, listAssignedTickets, PRIORIDAD_PESO, validateUpdateTicket } from './tickets.js';
export * from './ui/theme.js';
export * from './ui/components.js';
export * from './ui/FilterDropdown.js';
export * from './filters.js';
export * from './ui/layout/AppShell.js';
export * from './ui/layout/TopBar.js';
export * from './ui/layout/FilterBar.js';
export * from './ui/layout/Sidebar.js';
export * from './ui/layout/AppFooter.js';
export * from './ui/PasswordStrength.js';
export * from './ui/icons.js';
export * from './ui/Clock.js';
export * from './ui/FeedbackModal.js';
export * from './ui/charts/KpiCard.js';
export * from './ui/charts/DonutEstado.js';
export * from './ui/charts/BarsPrioridad.js';
export * from './ui/charts/AreaEvolucion.js';
export * from './ui/charts/HeatmapCarga.js';
export * from './ui/charts/TimelineAlertas.js';
export * from './ui/charts/PrediccionPicos.js';
export * from './ui/charts/PatronesCategoria.js';
export * from './ui/ticket/TicketComments.js';
export * from './dashboard.js';
export * from './export.js';
export * from './sla.js';
export * from './ia.js';
export * from './admin.js';
export * from './mesas.js';
export * from './categorias.js';
export * from './ui/perfil/PerfilCard.js';
